all:
  vars:
     ansible_python_interpreter: '/usr/bin/python3'
     publicIp:
        - {"name": MyVmMasterNfs-master, "ip":40.118.124.12, "hostname":MyVmMasterNfs-master}
        - {"name": MyVmWorkers-worker1, "ip":40.118.57.226, "hostname":MyVmWorkers-worker1}
        - {"name": MyVmWorkers-worker2, "ip":40.118.56.86, "hostname":MyVmWorkers-worker2}
  children:
    MasterNfs:
      hosts:
        MyVmMasterNfs-master:
          ansible_host: '{{publicIp[0].ip}}'
          ansible_user: adminUsername
    Workers:
      hosts:
        MyVmWorkers-worker1:
          ansible_host: '{{publicIp[1].ip}}'
          ansible_user: adminUsername
        MyVmWorkers-worker2:
          ansible_host: '{{publicIp[2].ip}}'
          ansible_user: adminUsername       
